### ISSUE TITLE
Terribly slow NAT

### ISSUE THREAD

**Issue by Miky028** [Aquantia/AQtion-esxi#14]
I'm using ESXi 6.5.0 Update 3, driver ESXi-1.6 release.
Distributed switch, uplink AQC107.
Distributed port group LAN (VLAN id 1).
Distributed port group Internet (VLAN id 4).
Virtual machine pfSense, 2 NICs, LAN - LAN, WAN - Internet.
When using IPv4 NAT web page is loading too long.
When using IPv6 web page is loaded instantly.
When I switch to different NIC for example Realtek NAT speed is fine.
All negotiate speeds are 1000Mbps I have only gigabit switch, for now.

For slow NAT is recommended disable HW checksum offload.
Has this driver problem with HW checksum offload? Or is any recommended settings?

**Comment by vinnie-ki** [comment]
I have got a similar problem. It's is not related to NAT in my situation. But I am experiencing also extremely slow download (rx) speeds (max. 4kbs) with a AQC107 card with ESXi 6.0 Update 2 and this driver. The upload speeds (tx) are as they should be. It's the same on 10 Gbit as on 1 Gbit speeds. I can rule out the cables or switches after some experimenting.

Anyone any idea?

Off course I will also try the card in passtrough mode with linux or windows later on to see if the problems will be the same.

Edit 15-12-2019

It may have something to do with this:

WARNING:  The AQtion driver compiles by default with the LRO (Large Receive
Offload) feature enabled.  This option offers the lowest CPU utilization for
receives, but is completely incompatible with *routing/ip forwarding* and
*bridging*.  If enabling ip forwarding or bridging is a requirement, it is
necessary to disable LRO using compile time options as noted in the LRO
section later in this document.  The result of not disabling LRO when combined
with ip forwarding or bridging can be low throughput or even a kernel panic.

 Disable GRO when routing/bridging
 ---------------------------------
 Due to a known kernel issue, GRO must be turned off when routing/bridging. 
 Its can be done with command:
 
 ethtool -K <ethX> gro off
 
 Disable LRO when routing/bridging
 ---------------------------------
 Due to a known kernel issue, LRO must be turned off when routing/bridging. 
 Its can be done with command:
 
 ethtool -K <ethX> lro off

Unfortunately the ethtool commands to turn of GRO or LRO don't work on ESXi.

**Comment by marcbou** [comment]
Here the slow download issue typically happens in guests which have TCP timestamps disabled (echo 0 > /proc/sys/net/ipv4/tcp_timestamps), enabling tcp timestamps (echo 1 > /proc/sys/net/ipv4/tcp_timestamps) seems to work a little better. 

Is it a bug or another side-effect of GRO/LRO? If ethtool cannot disable them on ESXI, can another way to do this be provided please ? (aside from recompiling the driver of course).

**Comment by dimbez** [comment]
Hello, @Miky028. Sorry for the delayed response. Actually HW offload disabling is not supported in vmkinux driver. For better performance, please update driver to native. You can find it at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)
